# Generated by Django 5.2.4 on 2025-07-07 18:14

import apps.backend.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("create_credential", "Created Credential"),
                            ("view_credential", "Viewed Credential"),
                            ("update_credential", "Updated Credential"),
                            ("delete_credential", "Deleted Credential"),
                            ("create_note", "Created Note"),
                            ("view_note", "Viewed Note"),
                            ("update_note", "Updated Note"),
                            ("delete_note", "Deleted Note"),
                            ("export_data", "Exported Data"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Descriptive name for this credential", max_length=255
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("website", "Website/App"),
                            ("email", "Email Account"),
                            ("social", "Social Media"),
                            ("banking", "Banking/Finance"),
                            ("work", "Work Related"),
                            ("personal", "Personal"),
                            ("server", "Server/Database"),
                            ("api", "API Key"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True, help_text="Website URL if applicable", null=True
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "password_encrypted",
                    models.TextField(help_text="Encrypted password"),
                ),
                (
                    "secret_key_encrypted",
                    models.TextField(
                        blank=True, help_text="Encrypted secret key or 2FA", null=True
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Credentials",
                "ordering": ["-updated_at"],
            },
            bases=(models.Model, apps.backend.models.EncryptionMixin),
        ),
        migrations.CreateModel(
            name="SecureNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content_encrypted",
                    models.TextField(help_text="Encrypted note content"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("work", "Work"),
                            ("financial", "Financial"),
                            ("medical", "Medical"),
                            ("legal", "Legal"),
                            ("technical", "Technical"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=50,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secure_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Secure Notes",
                "ordering": ["-updated_at"],
            },
            bases=(models.Model, apps.backend.models.EncryptionMixin),
        ),
    ]
